{% set name = "types-Pillow" %}
{% set version = "9.4.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-Pillow-{{ version }}.tar.gz
  sha256: ef8a823638ceb765a144a98a2f816b8912da0337c5c2556d33774f1434f9918c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/PIL-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for Pillow
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
