{% set name = "types-Pillow" %}
{% set version = "9.0.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-Pillow-{{ version }}.tar.gz
  sha256: 270c5a1ce94f3d38ab9f603aa816573d231195f18d179f67f2501a8c9443275c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/PIL-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for Pillow
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
